name: raw

on:
  push:
    branches: [develop]

jobs:
  staging_build_and_push:
    name: raw Build and Push
    runs-on: ubuntu-latest
    container: docker:20-dind
    steps:
      - uses: actions/checkout@v2
      - run: |
          apk add util-linux pciutils usbutils coreutils binutils findutils grep bash
          apk add python3
          apk add --update py3-pip
          pip3 install awscli
          chmod -R +x ./CI/scripts
          bash ./CI/scripts/build_and_push.sh raw
  staging_plan:
    name: raw Plan
    needs: staging_build_and_push
    runs-on: ubuntu-latest
    container: ronya3data/rony-ci:0.0.1-terraform1.0.3
    steps:
      - uses: actions/checkout@v2
      - name: terraform plan
        run: |
          chmod -R +x ./CI/scripts
          ./CI/scripts/plan.sh raw
  staging_apply:
    name: raw Apply
    needs: staging_plan
    runs-on: ubuntu-latest
    container: ronya3data/rony-ci:0.0.1-terraform1.0.3
    steps:
      - uses: actions/checkout@v2
      - name: terraform apply
        run: |
          chmod -R +x ./CI/scripts
          ./CI/scripts/apply.sh raw -auto-approve
env: 
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.email": "@gmail.com"
